/* Go version of hem2md. Go has better UTF-8 support than Perl.
 * (c) Chris Pinnock 2024
 *
 * Ming Vase license.
 * If it breaks, it doesn't matter how expensive it is for you:
 * you get to keep the pieces. No warranty whatsoever.
 */

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

var warning = true

func processFile(file string) {

	// Open the file and decode the JSON
	bytes, err := os.ReadFile(file)

	if err != nil {
		panic(err)
	}

	if warning {
		fmt.Printf("\n<!-- This file has been automatically generated by hem2md -->\n\n")
	}

	var document map[string]interface{}
	err = json.Unmarshal(bytes, &document)
	fmt.Println(document)

	strs := document["blocks"].([]interface{})
	fmt.Println(strs)

	// Traverse the blocks

}

func main() {

	nPtr := flag.Bool("n", false, "suppress HTML warning comments")

	flag.Parse()
	if *nPtr {
		warning = false
	}

	ags := flag.Args()

	for i := 0; i < len(ags); i++ {
		processFile(ags[i])
	}

}
